Ag cuda 12.1 more fixes
deeplearning4j/deeplearning4j pull request #10016
Opened 2023-07-27 11:26 UTC by agibsonccc

## What changes were proposed in this pull request?

Fixes misc test issues including:
1. diag scalar case (allows rank 0 arrays)
2. loss functions
3. reduction arrays don't throw exceptions on rank 0 arrays anymore
## How was this patch tested?

Ran c++ tests

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.konduit.ai/multi-project/how-to-guides/contribute/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ X] Created tests for any significant new code additions.
- [X ] Relevant tests for your changes are passing.

2023-07-27 13:03 UTC, treo requested changes
Once again, you've got quite a few stray prints all over the place.

2023-07-27 20:57 UTC, agibsonccc commented
Did a quick commented code/print scan and removed quite a bit.

2023-07-28 07:00 UTC, treo requested changes

2023-07-28 07:00 UTC, treo commented on libnd4j/include/array/NDArray.hXX
> +    sd_printf("Start is %d and stop is %d\n",start,stop);
still some more stray prints

2023-07-28 07:00 UTC, treo commented on libnd4j/include/array/NDArray.hXX
> +      sd_printf("data type is %s e is %d offsets[%d] is %d and offsets[%d] is %d\n",DataTypeUtils::asString(dtype).c_str(),e,e,offsets[e],e+1,offsets[e+1]);
still some more stray prints

2023-07-28 07:26 UTC, treo requested changes

2023-07-28 07:26 UTC, treo commented on libnd4j/include/ops/declarable/helpers/cuda/svd.cu
> +  sd_print("svdJcb\n");
yet another stray print.

2023-07-28 07:26 UTC, treo commented on libnd4j/include/ops/declarable/helpers/cuda/svd.cu
> +  sd_print("Before calcUV\n");
and one more

2023-07-28 07:26 UTC, treo commented on libnd4j/include/ops/declarable/helpers/cuda/svd.cu
> +    sd_print("before calcUV\n");
and more

2023-07-28 07:26 UTC, treo commented on libnd4j/include/ops/declarable/helpers/cuda/svd.cu
> +  sd_print("before buffer\n");
and more

2023-07-28 07:26 UTC, treo commented on libnd4j/include/ops/declarable/helpers/cuda/svd.cu
> +  sd_print("Buffer size\n");
and more

2023-07-28 07:26 UTC, treo commented on libnd4j/include/ops/declarable/helpers/cuda/svd.cu
> +  sd_print("manager synchronize\n");
and more

2023-07-28 07:26 UTC, treo commented on libnd4j/include/ops/declarable/helpers/cuda/svd.cu
> +  sd_print("Before free\n");
and more

2023-07-28 07:26 UTC, treo commented on libnd4j/include/ops/declarable/helpers/cuda/svd.cu
> +  sd_print("destroyed\n");
and more

2023-07-29 05:13 UTC, agibsonccc commented
@treo  done

2023-07-29 08:39 UTC, treo approved these changes

2023-07-29 08:46 UTC, merged