Add reshape no copy (reshape  in java ported to c++)
deeplearning4j/deeplearning4j pull request #10123
Opened 2024-10-22 11:59 UTC by agibsonccc

## What changes were proposed in this pull request?

Some aspects of reshape assumed many things about how the java reshape worked.
This adds an explicit op for that behavior to allow proper c++ delegation/abstraction
when reshaping ndarrays.

## How was this patch tested?

Manually with existing tests.
## Quick checklist

The following checklist helps ensure your PR is complete:

- [ X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.konduit.ai/multi-project/how-to-guides/contribute/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X ] Created tests for any significant new code additions.
- [X ] Relevant tests for your changes are passing.

2024-10-24 07:20 UTC, treo requested changes
This needs a tiny bit of cleanup.

2024-10-24 07:20 UTC, treo commented on libnd4j/include/array/ArrayOptions.h
> +#define ARRAY_IS_VIEW 33554432
Looks like a PR breakout bug? The constant is defined twice.

2024-10-24 07:20 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/shape/PaddingUtils.java
> +    // ... [Previous methods remain unchanged] ...
Looks like a co-pilot mistake?

2024-11-05 01:56 UTC, agibsonccc commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/shape/PaddingUtils.java
> +    // ... [Previous methods remain unchanged] ...
Just left over. Thanks for flagging!

2024-11-06 07:11 UTC, treo approved these changes

2024-11-06 07:38 UTC, merged