Corrected capital case for Activations, changed from "Tanh" To "TanH"
deeplearning4j/deeplearning4j pull request #8289
Opened 2019-10-14 18:05 UTC by yptheangel

Signed-off-by: yptheangel <choowilson93@gmail.com>

## What changes were proposed in this pull request?

Changes are targeted to issue "DL4J: Standardize activation function class capitalization #8279"
Changed the the "h" to "H" for "ActivationRationalTanh" and "ActivationRectifiedTanh" only in relevant files.

## How was this patch tested?

No additional test was done.

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

Note: I am uncertain on how to test the changes because I usually use the compiled jar files from Maven, I am willing to try to build from source if you could share some steps.

2019-12-06 03:28 UTC, agibsonccc requested changes
@yptheangel can you please add the corresponding change for the bp ops of this as well?

2019-12-10 15:22 UTC, yptheangel commented
Ok, let me do a lil bit of digging, first timer on the codebase

2019-12-10 15:50 UTC, yptheangel commented
![capitalcase](https://user-images.githubusercontent.com/30103695/70544802-a0d4a400-1ba7-11ea-8f2d-582330c90393.png)

@agibsonccc should I change the bp ops only (light green color) or also the ones without bpops(dark green color)?

2019-12-28 06:03 UTC, agibsonccc commented
@yptheangel sorry didn't see this. Thanks @saudet  Change ones with and without bpops.

2020-08-01 23:50 UTC, agibsonccc commented
Closing due to lack of activity.

2020-08-01 23:50 UTC, closed without merging