Minor github actions updates for snapshots
deeplearning4j/deeplearning4j pull request #9281
Opened 2021-05-02 10:57 UTC by agibsonccc

## What changes were proposed in this pull request?
Minor github actions fixes, snapshot fixes from past PRs.
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

2021-05-04 07:54 UTC, treo requested changes
Is the hack also needed when building locally? I guess you don't have libgomp in /usr/lib there either. If you want the hack to stay as brittle as it is (so it gets revisited when it breaks) feel free to keep it as is.

As for the other comment, the change looks unintended, so I'm flagging it for you so you can make sure it is supposed to be like that.

2021-05-04 07:54 UTC, treo commented on .github/workflows/build-deploy-linux-x86_64.yml
> +          sudo cp  /usr/lib/gcc/x86_64-linux-gnu/5.5.0/libgomp.so /usr/lib
If you want to make the hack hackier, you can replace the version this with
```
sudo cp /usr/lib/gcc/x86_64-linux-gnu/`gcc --version | head -n 1 | grep -o '[^ ]*$'` /usr/lib
```

2021-05-04 07:54 UTC, treo commented on .github/workflows/build-deploy-windows-cuda-11.2.yml
> +        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}MemoryTrackerTest
This looks unintended

2021-05-04 09:40 UTC, agibsonccc commented
@treo  not sure. That being said, the presets are configured to look in certain directories for each platform. As it stands, it only looks in a few places for libraries to include. Basically, for each platform each presets has a preload configured which are designated libraries to be bundled with the jar file. The paths configured for linux-x86_64 preloads are only a few locations. This won't matter to end users,  but it is something to document across different OSes people might be building on.

2021-05-06 01:51 UTC, agibsonccc commented
@treo  added new changes mind taking a look?

2021-05-06 09:25 UTC, treo approved these changes
I suggest you also create an issue to find a better solution for your hack later.

2021-05-06 23:20 UTC, merged