Update LayerValidation.java
deeplearning4j/deeplearning4j pull request #9286
Opened 2021-05-02 12:50 UTC by agibsonccc

## What changes were proposed in this pull request?
Updates LayerValidation to avoid ConcurrentModificationException by 
copying the results and setting the new result on the layer conf instead.
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

2021-05-03 09:21 UTC, treo requested changes
While this solves the symptom, I'm not sure it is the actual solution to the problem.

The situation when the list being iterated over being modified by that code should only ever happen when they are identical, and if they are identical, that entire part is not necessary. 

I think you need to dig deeper to understand why the situation happens in the first place, and then fix the root cause.

2021-05-05 02:24 UTC, agibsonccc commented
@treo  the change was introduced here: https://github.com/eclipse/deeplearning4j/pull/9252/commits/819f3b8c9d5377ed8c3031b4c519f0a3c13e65d3 - the fix was connected to: https://github.com/eclipse/deeplearning4j/issues/9050 0 it's only invoked here: https://github.com/eclipse/deeplearning4j/issues/9050

It appears to be due to sharing references to the same list across layers, similar to what is done with dropout, I added a copy constructor here: https://github.com/eclipse/deeplearning4j/blob/ba10a09c19c94973b15a73a3cbf39bf75888d2ee/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/NeuralNetConfiguration.java#L1175

2021-05-05 08:01 UTC, treo commented
With the copy constructor added, I think the other "fix" you introduced earlier isn't necessary anymore.

2021-05-06 04:17 UTC, agibsonccc commented
@treo Ran this with GradientCheckTests#testGradientWeightDecay as the failing test case and it seems to work now. There's a subtle issue when using for each when modifying the regularizations. I'm going to keep those in. The original fix was for an actual real problem we had with regularizations.

2021-05-06 09:08 UTC, treo approved these changes

2021-05-06 09:14 UTC, merged