Supplants https://github.com/eclipse/deeplearning4j/pull/9292
deeplearning4j/deeplearning4j pull request #9298
Opened 2021-05-09 22:40 UTC by agibsonccc

## What changes were proposed in this pull request?
Implements the ADR: #9290

Adds github workflows for a matrix based build structure for different classifiers.

## How was this patch tested?
Manually on GH actions

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X ] Created tests for any significant new code additions.
- [ X] Relevant tests for your changes are passing.

2021-05-10 07:17 UTC, treo requested changes
It looks like something went wrong when you were trying to separate out changes, so you've got merge artifacts all over the place. 

I've flagged them as comments so you just need to go through all of them and fix it. But I'd suggest you grep for `<<<<<<<` and see if there is something more left.

2021-05-10 07:17 UTC, treo commented on .github/workflows/build-deploy-linux-cuda-11.0.yml
> +>>>>>>> Stashed changes
Merge artifacts.

2021-05-10 07:17 UTC, treo commented on .github/workflows/build-deploy-linux-cuda-11.0.yml
> +>>>>>>> Stashed changes
more merge artifacts

2021-05-10 07:17 UTC, treo commented on .github/workflows/build-deploy-linux-cuda-11.2.yml
> +>>>>>>> Stashed changes
And even more

2021-05-10 07:17 UTC, treo commented on .github/workflows/build-deploy-linux-cuda-11.2.yml
> +>>>>>>> Stashed changes
And More

2021-05-10 07:17 UTC, treo commented on .github/workflows/build-deploy-linux-x86_64.yml
> +<<<<<<< Updated upstream
More merge artifacts here.

2021-05-10 07:17 UTC, treo commented on .github/workflows/build-deploy-windows-cuda-11.0.yml
> +>>>>>>> Stashed changes
some more

2021-05-10 07:17 UTC, treo commented on .github/workflows/build-deploy-windows-cuda-11.2.yml
> +>>>>>>> Stashed changes
.

2021-05-10 07:17 UTC, treo commented on .github/workflows/build-deploy-windows-cuda-11.2.yml
> +>>>>>>> Stashed changes
.

2021-05-10 07:17 UTC, treo commented on .github/workflows/build-deploy-windows.yml
> +>>>>>>> Stashed changes
.

2021-05-10 08:16 UTC, treo requested changes
Just one more question and a comment.

2021-05-10 08:16 UTC, treo commented on .github/workflows/build-deploy-linux-x86_64.yml
> +          sudo cp "${LIBGOMP_PATH}" /usr/lib
The comment doesn't make sense in this context anymore.

2021-05-10 08:16 UTC, treo commented on .github/workflows/build-deploy-linux-cuda-11.0.yml
> +
I'd probably split this some more into a base command and extension parameters. 

Something like
```bash
if [ "${HELPER}" != '' ] && [ "${EXTENSION}" != '' ]; then
    mvn_ext="-Djavacpp.platform.extension=-${{ matrix.helper }}-${{ matrix.extension }} -Dlibnd4j.helper=${{ matrix.helper }} -Dlibnd4j.extension=${{ matrix.extension }}"
elif [ "${HELPER}" != '' ]; then
    mvn_ext="-Djavacpp.platform.extension=-${{ matrix.helper }} -Dlibnd4j.helper=${{ matrix.helper }} -Dlibnd4j.extension=${{ matrix.extension }}"
else
    mvn_ext="-Djavacpp.platform.extension=${{ matrix.extension }} -Dlibnd4j.helper=${{ matrix.helper }} -Dlibnd4j.extension=${{ matrix.extension }}"
fi

command="mvn -Possrh ${mvn_ext} -Dlibnd4j.buildThreads=${{ github.event.inputs.buildThreads }}  -Djavacpp.platform=linux-x86_64 -Dlibnd4j.chip=cuda --also-make -Pcuda clean --batch-mode package deploy -DskipTests"
```

And having refactored it like that, I wonder, why do you even specify those values in the cases where they aren't defined?

2021-05-10 08:28 UTC, agibsonccc commented on .github/workflows/build-deploy-linux-cuda-11.0.yml
> +
@treo  that was mainly due to environment variable/GH actions debugging. I refactored based on your comments there.

2021-05-10 09:44 UTC, treo requested changes
A few more places where you can apply that same refactoring. And if ideally, it would be more like the following:
```
if [ "${HELPER}" != '' ] && [ "${EXTENSION}" != '' ]; then
    mvn_ext="-Djavacpp.platform.extension=-${{ matrix.helper }}-${{ matrix.extension }} -Dlibnd4j.helper=${{ matrix.helper }} -Dlibnd4j.extension=${{ matrix.extension }}"
elif [ "${HELPER}" != '' ]; then
    mvn_ext="-Djavacpp.platform.extension=-${{ matrix.helper }} -Dlibnd4j.helper=${{ matrix.helper }}"
else
    mvn_ext=""
fi
```

Or, if you need to have those things set to empty, make it explicit:
```
if [ "${HELPER}" != '' ] && [ "${EXTENSION}" != '' ]; then
    mvn_ext="-Djavacpp.platform.extension=-${{ matrix.helper }}-${{ matrix.extension }} -Dlibnd4j.helper=${{ matrix.helper }} -Dlibnd4j.extension=${{ matrix.extension }}"
elif [ "${HELPER}" != '' ]; then
    mvn_ext="-Djavacpp.platform.extension=-${{ matrix.helper }} -Dlibnd4j.helper=${{ matrix.helper }} -Dlibnd4j.extension="
else
    mvn_ext="-Djavacpp.platform.extension= -Dlibnd4j.helper= -Dlibnd4j.extension="
fi
```

2021-05-10 09:44 UTC, treo commented on .github/workflows/build-deploy-linux-x86_64.yml
> +             fi
Same kind of refactoring is possible here.

2021-05-10 09:44 UTC, treo commented on .github/workflows/build-deploy-mac.yml
> +          fi
and here

2021-05-10 09:44 UTC, treo commented on .github/workflows/build-deploy-windows-cuda-11.0.yml
> +          }
and here

2021-05-10 09:44 UTC, treo commented on .github/workflows/build-deploy-windows-cuda-11.2.yml
> +          }
and here

2021-05-10 09:44 UTC, treo commented on .github/workflows/build-deploy-windows.yml
> +
and here

2021-05-10 10:55 UTC, agibsonccc commented
@saudet  mainly flagging the presets changes for you.

2021-05-11 00:49 UTC, saudet approved these changes, later dismissed

2021-05-12 06:08 UTC, treo approved these changes

2021-05-12 06:16 UTC, merged