WIP: Cuda 10.2 cross compile for nano
deeplearning4j/deeplearning4j pull request #9413
Opened 2021-08-05 12:44 UTC by agibsonccc

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

2021-08-11 07:14 UTC, treo requested changes

2021-08-11 07:14 UTC, treo commented on .github/workflows/build-deploy-linux-cuda-10.2-arm64.yml
> +        default: 1.0.0-M1
Shouldn't this be 1.0.0-M1.1?

2021-08-11 15:43 UTC, quickwritereader approved these changes
though I believe it would be great if you changed hardcoded URL and versions to generated/external arguments 
but looks good to me

2021-08-11 15:43 UTC, quickwritereader commented on libnd4j/pi_build.sh
> +		CUDA_TARGET_STUB_URL=https://github.com/KonduitAI/jetson-release/releases/download/0.1.0/aarch64_linux_cuda_10.2_cudnn8.2.tar.gz
it would be great if you had a generated URL based on versions here.

2021-08-11 15:43 UTC, quickwritereader commented on libnd4j/pi_build.sh
> +		message "Moving  ${CUDA_TARGET_STUBS}/aarch64_linux_cuda_10.2_cudnn8.2 to ${CUDA_TARGET_STUBS}/aarch64-linux/"
the same here, hardcoded versions

2021-08-12 13:44 UTC, agibsonccc commented on .github/workflows/build-deploy-linux-cuda-10.2-arm64.yml
> +        default: 1.0.0-M1
I can do a separate PR for the next version. For now I just need to test this ci work flow. It's a new file.

2021-08-12 15:14 UTC, treo approved these changes

2021-08-12 21:10 UTC, merged