Java side changes for model import and samediff uptraining
deeplearning4j/deeplearning4j pull request #9501
Opened 2021-10-27 08:03 UTC by agibsonccc

## What changes were proposed in this pull request?
java side changes for model import including:
1. Automatic removal of no ops. We need this for automatic differentiation to work properly.
2. Dynamic custom op remove getNumOutputs() which breaks shapes resolution.
3. Adds more type conversions for various fields
4. Adds null check for arrays in SDVariable
5. Better debugging errors for certain op serialization issues
6.  Adds new set shape op
7. Adds new configureFromArguments() for model import handling definitions of configuration objects such as MMulTranspose,Conv2D/3DConfig
8.  Update Flatten and Flatten2D gradients to reflect a proper conversion of the original shape  when going backward
9. Update base reduction custom op to properly add keepDims argument as a boolean.
10. Add missing constructors for splitV for code gen
11. Misc Windows build fixes
12. Updates onnx import uptraining test case for lenet
13.  Fixes reshape bug in c++ when specifying an ndarray for the shape.
14. Fix up reduce test failures with dimensional inputs, big focus around variance/standard deviation related ops including moments, various reduce backpropagation ops 
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

2021-10-27 08:17 UTC, treo requested changes

2021-10-27 08:17 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/layers/convolution/Conv3D.java
> +        if (config == null && !iArguments.isEmpty()) {
Shouldn't this have the same kind of check as https://github.com/eclipse/deeplearning4j/pull/9501/files#diff-e8b421fce15c6fe13280bf5040a342b65769c2016bbdd5429916c10310b9cdfaR275-R277 ?

2021-10-27 08:17 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/layers/convolution/MaxPooling2D.java
> +            config = Pooling2DConfig.builder()
as above, I guess the same kind of check as in https://github.com/eclipse/deeplearning4j/pull/9501/files#diff-e8b421fce15c6fe13280bf5040a342b65769c2016bbdd5429916c10310b9cdfaR275-R277 would be useful here too.

2021-10-27 08:17 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/layers/convolution/Pooling2D.java
> +           config = Pooling2DConfig.builder()
as above, I guess the same kind of check as in https://github.com/eclipse/deeplearning4j/pull/9501/files#diff-e8b421fce15c6fe13280bf5040a342b65769c2016bbdd5429916c10310b9cdfaR275-R277 would be useful here too.

2021-10-27 17:25 UTC, treo submitted a review, later dismissed

2021-10-29 13:18 UTC, agibsonccc commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/SDVariable.java
@treo this might be a suspect fix for you. Please feel free to take a look. I did this so we could be a bit more flexible with placeholders. Not being able to have an unknown data type for a placeholder didn't make much sense to me.

2021-10-29 13:18 UTC, agibsonccc commented on nd4j/samediff-import/samediff-import-api/src/main/kotlin/org/nd4j/samediff/frameworkimport/ImportGraph.kt
> +        val newNodeList =  ArrayList<IRNode<NODE_TYPE, TENSOR_TYPE, ATTR_DEF_TYPE, ATTR_VALUE_TYPE, DATA_TYPE>>()
@treo this is another change that could be suspect...for my test case I ran in to a bunch of problems with :0 as a suffix. You run in to this with tensorflow models as well as tf onnx models.

2021-10-29 16:38 UTC, treo requested changes
Only one change request: Please turn the magic numbers for ordering into constants, that way you can put some documentation on the constant.

2021-10-29 16:38 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/Reshape.java
> +        addIArgument(-99);
Can we turn this magic number into a constant?

2021-10-31 07:54 UTC, treo requested changes
You've missed on point with the constants, and apparently you still had focus on your IDE when you started typing about something else in the Ops definition.

2021-10-31 07:54 UTC, treo commented on contrib/codegen-tools/codegen/src/main/ops/org/nd4j/codegen/ops/SDBaseOps.kt
> +        Arg(BOOL, "kemathepDims") { description = "If true: keep the dimensions that are reduced on (as size 1). False: remove the reduction dimensions"; defaultValue=false }
wat?

2021-10-31 07:54 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/Reshape.java
> +        addIArgument(-99);
Forgot one here.

2021-10-31 13:23 UTC, agibsonccc commented
@quickwritereader there's quite a few changes around reduce operations and dimensions. Could you do a quick scan on the libnd4j bits? Thanks!

2021-10-31 13:30 UTC, treo approved these changes
Didn't look too close at the C++ parts, but otherwise it looks OK now :)

2021-10-31 13:36 UTC, quickwritereader approved these changes
lgtm. But did we decide to keep defined Cygwin there?.
well done.  if it passing tests merge it so I will be able to rebase new refactorings against it

2021-10-31 21:39 UTC, merged

2021-10-31 23:21 UTC, agibsonccc commented
@quickwritereader I need to do a part 2 to improve some of the tests yet, but this is a big improvement yes.