Ensure gradient check passes with scalars
deeplearning4j/deeplearning4j pull request #9507
Opened 2021-11-01 07:56 UTC by agibsonccc

## What changes were proposed in this pull request?
In our gradient calculations with reduce operations, scalars fail gradient checks due to ignoring dimensions.
This PR fixes that in various gradient calculations.
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

2021-11-01 08:06 UTC, quickwritereader approved these changes, later dismissed

2021-11-01 08:26 UTC, quickwritereader approved these changes, later dismissed

2021-11-04 07:40 UTC, treo requested changes
It looks like you've got a debug println leftover and the eps value seems to be very high,

2021-11-04 07:40 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/validation/functions/EqualityFn.java
> +    private double eps = 1e-3;
That's a very high value for an eps.

2021-11-04 07:40 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/reduce3/EuclideanDistance.java
> +        System.out.println();
huh?

2021-11-04 09:43 UTC, treo approved these changes

2021-11-04 09:54 UTC, merged