Minor aurora fixes and rename
deeplearning4j/deeplearning4j pull request #9542
Opened 2021-11-29 10:47 UTC by agibsonccc

## What changes were proposed in this pull request?
Minor aurora rename import fixes.
Introduces a workaround to allow you to specify an absolute path to a compiled libnd4j binary
if not bundled.
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ X] Created tests for any significant new code additions.
- [X ] Relevant tests for your changes are passing.

2021-11-29 13:11 UTC, treo requested changes
Got a few more questions

2021-11-29 13:11 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java
> +            //deviceNativeOps.initializeDevicesAndFunctions();
This looks weird. Why don't we want to initialize here? And if we really don't want that, maybe remove it entirely instead of commenting it out.

2021-11-29 13:11 UTC, treo commented on nd4j/nd4j-backends/nd4j-backend-impls/nd4j-aurora/src/main/java/org/nd4j/linalg/aurora/AuroraBackend.java
> +        return BACKEND_PRIORITY_GPU;
Maybe give it its own priority level?

2021-11-29 13:40 UTC, agibsonccc commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java
> +            //deviceNativeOps.initializeDevicesAndFunctions();
@treo ah yeah that was me testing a load_symbol problem and seeing what the source was. Uncommented now.

2021-11-29 13:42 UTC, agibsonccc commented on nd4j/nd4j-backends/nd4j-backend-impls/nd4j-aurora/src/main/java/org/nd4j/linalg/aurora/AuroraBackend.java
> +        return BACKEND_PRIORITY_GPU;
Done

2021-11-29 15:14 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java
> +            //deviceNativeOps.initializeDevicesAndFunctions();
huh, as far as I can tell, this is still the same?

2021-11-30 07:37 UTC, treo approved these changes, later dismissed

2021-12-01 08:26 UTC, treo approved these changes

2021-12-01 08:27 UTC, merged