Follow up test fixes (dimensions as ndarray inputs)/misc fixes
deeplearning4j/deeplearning4j pull request #9584
Opened 2021-12-27 13:51 UTC by agibsonccc

Java imports clean up, dimensions related fixes for resolving dimensi…ons based on multiple inputs

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

2021-12-27 15:19 UTC, treo requested changes
A few things here:

1. You've got another test result file in here: `libnd4j/tests_cpu/surefire-reports/TEST-cpu-results.xml`
2. Why are you using fully qualified class names for standard library like String in the IR files? 
3. It looks like you've also kept a few more tempFiles from tests around in the platform-tests directory

2021-12-27 15:19 UTC, treo commented on nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/pom.xml
> +                    </compilerOptions>-->
I guess you forgot to remove this?

2021-12-27 15:19 UTC, treo commented on platform-tests/src/test/java/org/nd4j/imports/tfgraphs/TFGraphTestAllHelper.java
> +        }
Lots of commented out code here and an empty println. 

This doesn't look merge ready.

2021-12-27 22:18 UTC, agibsonccc commented
@treo ok got most of the nits there. Regarding the IR classes, those are auto generated. I'm not sure if you can configure the protobuf generator to not do that. I'll check though.

2021-12-29 08:12 UTC, treo approved these changes

2021-12-29 08:14 UTC, merged