Add new onnx support, control flow ops
deeplearning4j/deeplearning4j pull request #9663
Opened 2022-04-08 23:48 UTC by agibsonccc

## What changes were proposed in this pull request?
1. Add new control flow ops for onnx
2. Add new proprietary pytorch ops to onnx (AliasWithName,..)
3. Add new invoke lambda/control flow allowing for running loops on a lambda
4. 
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

2022-04-09 05:42 UTC, treo requested changes
Quite a large PR, so it is likely that I've glossed over things. 

The changes I'm requesting are mostly for the ADR. 

Take the other comments on the code more as questions.

2022-04-09 05:42 UTC, treo commented on ADRs/0018 - SDValue.md
> +execute operations within a graph.
Please use present tense in the Proposal section.

Also please ensure that the Markdown renders properly on Github. In particular, have a space after the final `#`, so headlines show up as actual headlines.

2022-04-09 05:42 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/functions/DifferentialFunction.java
> +            out[i] = outputVars[i] == null ? "" : outputVars[i].name();
Do we need the `null` case anywhere? Or wouldn't it make more sense to handle `null` in the `outputVariables()` function, so that everything downstream doesn't need to have special case handling?

2022-04-10 10:40 UTC, agibsonccc commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/functions/DifferentialFunction.java
> +            out[i] = outputVars[i] == null ? "" : outputVars[i].name();
Null comes mostly come the Switch op where 1 branch is null and the other isn't. I'd want to think on this one a bit. I'm not clear if there's anything in specific I'd want to do with the null case beyond that.

2022-04-11 16:04 UTC, treo approved these changes
The proposed additions look reasonable. Can't really comment on the UX of it though, as I haven't tried using it yet.

2022-04-11 21:58 UTC, merged