Minor fixes
deeplearning4j/deeplearning4j pull request #9674
Opened 2022-04-19 13:33 UTC by agibsonccc

## What changes were proposed in this pull request?
1. Fixes #9669 
2. Add back missing code gen declarations for topk
3. Fix codegen to allow gather/gathernd to work with non numerical ndarrays (strings)
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

2022-04-20 07:33 UTC, treo requested changes

2022-04-20 07:33 UTC, treo commented on libnd4j/include/array/NDArray.hXX
> +  if (isS()) throw std::runtime_error("NDArray::sumNumber: you can't use this method on String array!");
Wrong error message.

2022-04-20 07:33 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/ops/SDMath.java
> +   * For rank 2 matrices, the output is a scalar vith the trace - i.e., sum of the main diagonal.<br>
Reintroducing a typo that was previously fixed? 

Given that this is a generated namespace, I guess you'll need to fix the typo in the definition code.

2022-04-20 07:33 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/ops/SDMath.java
> +   * For rank 2 matrices, the output is a scalar vith the trace - i.e., sum of the main diagonal.<br>
Reintroducing a typo that was previously fixed? 

Given that this is a generated namespace, I guess you'll need to fix the typo in the definition code.

2022-04-20 07:33 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/custom/FusedBatchNorm.java
> +    }
Huh? We don't have backprop for this?

2022-04-20 07:33 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/custom/FusedBatchNorm.java
> +    }
Huh? We don't have backprop for this?

2022-04-27 07:48 UTC, agibsonccc commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/custom/FusedBatchNorm.java
> +    }
Nope

2022-04-27 08:01 UTC, treo requested changes

2022-04-27 08:01 UTC, treo commented on libnd4j/include/array/NDArray.hXX
> +  if (isS()) throw std::runtime_error("NDArray::sumNumber: you can't use this method on String array!");
Wrong error message.

2022-04-27 08:01 UTC, treo commented on deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/resources/sentiment/sentiwordnet.txt
> +n	09584218	0	0	witharr#1 withar#1 vidar#1	(Norse mythology) one of the Aesir; son of Odin; avenges his parent by slaying Fenrir at Ragnarok
Now you've introduced new typos

2022-04-27 14:04 UTC, treo requested changes

2022-04-27 14:04 UTC, treo commented on deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/resources/sentiment/sentiwordnet.txt
> +n	11348946	0	0	trewithick#1 richard_trewithick#1	English engineer who built the first railway locomotive (1771-1833)
This needs to be reverted too. I thought at marking just one instance in this file would have been enough.

2022-04-29 23:51 UTC, quickwritereader approved these changes, later dismissed

2022-04-29 23:51 UTC, quickwritereader commented on libnd4j/include/ops/declarable/generic/tensor/create_view.cpp
> +  sd_printf("About to get variable 0\n",0);
sd_debug

2022-04-29 23:51 UTC, quickwritereader commented on libnd4j/include/ops/declarable/generic/tensor/create_view.cpp
> +  sd_printf("Obtained variable 0\n",0);
sd_debug

2022-04-29 23:51 UTC, quickwritereader commented on libnd4j/include/array/impl/DataBuffer.cpp
> +        _lenInBytes = 0;
was this file formatted with the clangformat-style that comes in the libnd4j folder?

2022-04-30 08:03 UTC, agibsonccc commented on libnd4j/include/ops/declarable/generic/tensor/create_view.cpp
> +  sd_printf("About to get variable 0\n",0);
@quickwritereader I removed those afterwards thanks for checking!

2022-04-30 08:04 UTC, agibsonccc commented on libnd4j/include/array/impl/DataBuffer.cpp
> +        _lenInBytes = 0;
done

2022-05-01 22:54 UTC, quickwritereader approved these changes, later dismissed

2022-05-03 15:45 UTC, treo reviewed
Still need to read and consider the ADRs, but I've flagged some places for a clean up that I've found while given the code a cursory glance.

2022-05-03 15:45 UTC, treo commented on libnd4j/include/ops/declarable/impl/DeclarableOp.cpp
> +  sd_printf("Pushing variable\n",0);
shouldn't this be an sd_debug? Same applies to other usages of sd_printf and printIndexedBuffer in this file

2022-05-03 15:45 UTC, treo commented on libnd4j/include/ops/declarable/impl/PlatformHelper.cpp
> +      throw std::runtime_error("Failed execution");
While "Failed execution" is a better message than "Boom", I wonder if we can't have something more descriptive here?

Also, Do we need to both print and throw an exception?

2022-05-03 15:45 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/Permute.java
> +        System.out.println();
Leftover from debugging?

2022-05-03 15:45 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/Slice.java
> +        System.out.println();
Leftover from debugging?

2022-05-04 06:30 UTC, treo requested changes
A bit more nitpicking

2022-05-04 06:30 UTC, treo commented on libnd4j/include/graph/impl/Context.cpp
> +      sd_printf("Context: After getting variable in push ndarray to variable space",0);
Still using sd_printf

2022-05-04 06:30 UTC, treo commented on libnd4j/include/graph/impl/Context.cpp
> +    sd_printf("Before ensure variable",0);
Still using sd_printf

2022-05-04 07:06 UTC, treo requested changes
Overall I agree with the proposals in the ADRs, but I'd like to have them a bit more fleshed out. I've added some additional questions in the appropriate places. 

Also a note on on style: The ADRs are meant to be records of decisions that have been made. For this reason the proposal should be talking about things as if it is describing the current state of the code. 

This means "We introduce..." , "We now [support]..." and phrases that talk about things that can be considered future-ish, should be well considered. Usually there is a better way to phrase it.

Another thing is that in the Dynamic Indexing ADR, most of the first paragraph of the proposal should probably be part of the context instead, as you're not describing not the actual proposal but give more context on what was there before.

2022-05-04 07:06 UTC, treo commented on ADRs/0021 - Create View.md
> +this is by default 0 most of the time since the value is only relevant for intervals.
Not quite sure what that means. If it is a constant, it should have the same value all of the time. 

Or is the above meant to represent the constructor signature for this op and here you're explaining what one of the argument values is?

2022-05-04 07:06 UTC, treo commented on ADRs/0021 - Create View.md
> +operation itself.
I think this should be explained a little bit better, in particular how this relates to the input representations above.

2022-05-04 07:06 UTC, treo commented on ADRs/0021 - Create View.md
> +* Similar in usage to indexes
Can you also explain how this view method differs from ND4J's? In particular what kinds of gotchas one might expect when switching between the two and how the API differs?

2022-05-04 07:06 UTC, treo commented on ADRs/0022 - Dynamic Indexing.md
> +1. Each index now as a concept of initialized(). This returns a boolean indicating whether the operation was initialized or not. Initialized usually means there are no negative values present in the
> Initialized **usually** means there are no negative values present in the index

Can there be any cases when there still can be negative values present? Or does it actually **always** mean that there are no negative values present?

2022-05-04 07:06 UTC, treo commented on ADRs/0022 - Dynamic Indexing.md
> +3. At runtime, upon use a deep copy of the index happens and then initialization will occur upon use relative to the ndarray using it.
Does this mean it is happening at the Java level? Or should this be done as late as possible and actually happen at the C++ level?

2022-05-04 10:05 UTC, agibsonccc commented on ADRs/0021 - Create View.md
> +this is by default 0 most of the time since the value is only relevant for intervals.
I explain that these are constant keys above. I clarified that now.

2022-05-04 14:49 UTC, quickwritereader submitted a review, later dismissed

2022-05-04 15:40 UTC, treo approved these changes

2022-05-04 15:40 UTC, merged