WIP: Fix issue with cache references improperly combined with control flow
deeplearning4j/deeplearning4j pull request #9706
Opened 2022-06-06 07:25 UTC by agibsonccc

## What changes were proposed in this pull request?
1. Fixes control flow caching issue.
The array cache manager returns references to arrays that need to be reused in subsequent iterations of  a loop. With the cache enabled we may use arrays in outputs which can break subsequent iterations of a loop variable.

2. Adds multinomial op for import.

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X ] Created tests for any significant new code additions.
- [ X] Relevant tests for your changes are passing.

2022-06-07 08:37 UTC, quickwritereader submitted a review, later dismissed

2022-06-08 08:19 UTC, treo requested changes

2022-06-08 08:19 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/internal/AbstractSession.java
> +                                //note: we omit break on purpose
This doesn't make sense. Do we omit break on purpose, or do we break?

2022-06-08 08:19 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/internal/InferenceSession.java
> +                    }*/
Please don't leave any commented out code behind.

2022-06-08 08:19 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/internal/InferenceSession.java
> +                //putNodeValue(sdValue, tArr);
commented out code

2022-06-08 08:19 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/internal/InferenceSession.java
> +            //putNodeValue(sdValue1, tArr);
commented out code

2022-06-08 08:19 UTC, treo commented on platform-tests/src/test/java/org/eclipse/deeplearning4j/nd4j/autodiff/samediff/MemoryMgrTest.java
> +    /*    ArrayCacheMemoryMgr mmgr = new ArrayCacheMemoryMgr();
commented out code

2022-06-09 07:02 UTC, treo approved these changes

2022-06-09 07:22 UTC, merged