WIP: Improve Skipgram performance
deeplearning4j/deeplearning4j pull request #9796
Opened 2022-09-30 12:05 UTC by agibsonccc

## What changes were proposed in this pull request?
Work on improving skipgram performance. There was an overall regression in performance from earlier versions after migrating to the c++ op.
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ X] Created tests for any significant new code additions.
- [ X] Relevant tests for your changes are passing.

2022-10-05 15:34 UTC, treo requested changes

2022-10-05 15:34 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java
> +        INDArray ret = createUninitialized(shape, Nd4j.order()).castTo(dataType); //INSTANCE.rand(shape, rng);
Please don't leave any left-over commented out code here.

2022-10-05 15:34 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java
> +    }
That looks quite repetitive, no way to rewrite this such that the `closeFlush` flag doesn't produce duplicate code?

2022-10-05 15:34 UTC, treo commented on platform-tests/src/test/java/org/deeplearning4j/models/paragraphvectors/ParagraphVectorsTest.java
> +     */       //assertEquals(vec,paragraphVectors);
Was this TODO handled?

2022-10-06 07:09 UTC, agibsonccc commented on platform-tests/src/test/java/org/deeplearning4j/models/paragraphvectors/ParagraphVectorsTest.java
> +     */       //assertEquals(vec,paragraphVectors);
Yes it was. Did clean up.

2022-10-06 07:09 UTC, agibsonccc commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java
> +        INDArray ret = createUninitialized(shape, Nd4j.order()).castTo(dataType); //INSTANCE.rand(shape, rng);
Both instances here were old code. I cleaned that up and replaced all duplicate usages of redundant in the tests.

2022-10-06 15:17 UTC, treo requested changes

2022-10-06 15:17 UTC, treo commented on nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java
> +        INDArray ret = createUninitialized(shape, Nd4j.order()).castTo(dataType); //INSTANCE.rand(shape, rng);
Please also remove the `//INSTANCE.rand(shape, rng);` in this line :)

2022-10-07 08:46 UTC, treo approved these changes

2022-10-07 08:46 UTC, merged